POST https://node-do-zero-w94q.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

//retorna todos os vídeos 
GET https://node-do-zero-w94q.onrender.com/videos  

//retorna vídeos com title específico como "node" 
//GET https://node-do-zero-w94q.onrender.com/videos?search=node 

###

PUT https://node-do-zero-w94q.onrender.com/videos/31213692-e25b-445e-b434-13e9036e3358
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o vídeo 01",
    "duration": 180
}

###

DELETE https://node-do-zero-w94q.onrender.com/videos/31213692-e25b-445e-b434-13e9036e3358
